services:
  db:
    image: mysql:8.0
    container_name: yeticave-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: yeticave
    ports:
      - "3307:3306"
    volumes:
      - yeticave_mysql_data:/var/lib/mysql

volumes:
  yeticave_mysql_data: